# Generated by Django 4.0.2 on 2022-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('startingbid', models.FloatField()),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=15)),
                ('dateuploaded', models.DateTimeField()),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
