# Generated by Django 4.0.2 on 2022-04-08 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctions_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dateuploaded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
