# Generated by Django 4.0.2 on 2022-04-11 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_dateuploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('dateofbid', models.DateTimeField(default=datetime.datetime.now)),
                ('auctionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentauction', to='auctions.auction')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('dateofbid', models.DateTimeField(default=datetime.datetime.now)),
                ('auctionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidauction', to='auctions.auction')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
