# Generated by Django 4.0.2 on 2022-04-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_userid_alter_auction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='userid',
        ),
    ]
