# Generated by Django 4.0.2 on 2022-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
