# Generated by Django 4.0.2 on 2022-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auction_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highestbid',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startingbid',
            field=models.FloatField(default=1),
        ),
    ]
