# Generated by Django 4.0.2 on 2022-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
